"""empty message

Revision ID: 404aee7bb3e7
Revises: 
Create Date: 2021-06-21 10:06:10.173000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404aee7bb3e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('addr', sa.String(length=50), nullable=True),
    sa.Column('age', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
