"""empty message

Revision ID: 96e86eb53b50
Revises: 404aee7bb3e7
Create Date: 2021-06-21 10:28:14.760663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e86eb53b50'
down_revision = '404aee7bb3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('addr', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('addr', 'user', ['addr'], unique=False)
    # ### end Alembic commands ###
